"""Single source of truth for TenderLab public editorial copy."""

from __future__ import annotations


PUBLIC_COPY = {
    "common": {
        "back_home_aria": "Volver al inicio",
        "navigation_aria": "Navegación principal",
        "nav_analyzer": "Analizador",
        "nav_lab": "Laboratorio",
        "release_label": "Versión beta",
    },
    "landing": {
        "meta_description": "Comprende cómo la fórmula económica modifica el resultado de una licitación pública.",
        "home_aria": "Inicio del proyecto Fórmulas de Valoración",
        "product_name": "Fórmulas de Valoración",
        "product_subtitle": "Licitación pública",
        "kicker": "Proyecto Fórmulas de Valoración",
        "title": "La importancia de la fórmula económica en la licitación pública",
        "subtitle": "Asignar 40 puntos al precio no asegura que realmente discriminen 40; la fórmula, las ofertas y las bajas extremas pueden cambiar radicalmente el resultado de una licitación.",
        "context_link": "¿Por qué ocurre esto? Entender las fórmulas de precio",
        "venn_alt": "Diagrama de equilibrio entre calidad, fiabilidad y buen precio",
        "profiles_aria": "Elegir perfil de análisis",
        "administration": {
            "label": "Administración pública",
            "title": "¿Qué fórmula de precio ayuda a seleccionar mejor oferta?",
            "body": "Compara fórmulas, curvas teóricas y casos reales para ver cómo se reparten los puntos y qué efecto producen las bajas extremas.",
            "cta": "Analizar y diseñar una fórmula",
        },
        "company": {
            "label": "Empresa licitadora",
            "title": "¿Tiene sentido presentarte con la baja que realmente puedes asumir?",
            "body": "Simula ofertas a partir de tus costes y capacidades reales para entender dónde compites con una fórmula concreta.",
            "cta": "Simular mi oferta",
        },
        "equations_aria": "Ejemplos de fórmulas económicas",
        "equations_kicker": "Base matemática",
        "equations_title": "De la ecuación al resultado real",
        "equations_cta": "Abrir el laboratorio teórico",
        "equations_alt": "Ejemplos provisionales de fórmulas económicas de valoración del precio",
        "explainer_kicker": "Dos espacios conectados",
        "explainer_title": "Fórmula, curva, ofertas, puntuación y adjudicación",
        "explainer_body": "El laboratorio permite comprender el comportamiento teórico de cada ecuación. El analizador muestra qué ocurre al aplicarla a licitaciones reales anonimizadas y permite ensayar cambios sin alterar los datos originales.",
        "explainer_analyzer_cta": "Explorar casos reales",
        "explainer_lab_cta": "Entender las fórmulas",
        "feedback_kicker": "Conversación abierta",
        "feedback_body": "Las observaciones profesionales ayudan a contrastar y mejorar la herramienta.",
        "feedback_cta": "Opinar, proponer un caso o contactar",
        "footer_legal": "Herramienta de análisis matemático. No sustituye el análisis jurídico de un expediente concreto.",
        "footer_author": "Desarrollado por Jorge Cejudo Podio",
    },
    "analysis": {
        "meta_description": "Analizador de casos reales de fórmulas de valoración económica.",
        "page_title": "Analizador de casos reales",
        "product_name": "Analizador de casos reales",
        "product_subtitle": "Fórmulas de Valoración",
        "case_strip_aria": "Datos principales del caso",
        "case_label": "Caso real",
        "profile_label": "Perfil",
        "profile_aria": "Perfil de análisis",
        "profile_administration": "Administración",
        "profile_company": "Empresa",
        "restore_case": "Restaurar caso real",
        "workspace_aria": "Puesto de análisis del caso",
        "controls_aria": "Controles de simulación",
        "controls_kicker": "Cambiar y observar",
        "loading_case": "Cargando caso…",
        "calculating": "Calculando…",
        "visible_formulas": "Fórmulas visibles",
        "parameters": "Parámetros",
        "expected_bmax": "Baja máxima esperada",
        "expected_bmax_value_aria": "Baja máxima esperada (valor)",
        "expected_bmax_help": "Hipótesis de trabajo, no dato real.",
        "offers": "Ofertas",
        "tender_price": "Precio de licitación",
        "price_points": "Puntos precio",
        "add_offer": "Añadir oferta",
        "what_if": "¿Qué pasa si…?",
        "add_extreme": "Añadir una baja extrema",
        "undo_simulation": "Deshacer simulación",
        "chart_kicker": "Curvas y ofertas reales",
        "chart_title": "Puntos obtenidos según la baja",
        "understand_formula": "Entender esta fórmula",
        "show_resulting_curve": "Mostrar curva resultante",
        "chart_svg_title": "Curvas de puntuación y ofertas del caso",
        "chart_svg_description": "El eje horizontal representa la baja porcentual y el vertical los puntos del criterio precio.",
        "active_formulas_aria": "Fórmulas activas",
        "represented_offers_aria": "Ofertas representadas",
        "selected_offer_help": "Selecciona un punto LIC-n para fijar sus datos.",
        "results_aria": "Resultados principales",
        "results_kicker": "Resultado actual",
        "rank_with": "Clasificar con",
        "simulated_winner": "Ganador simulado",
        "technical_best": "Mejor técnicamente",
        "cheapest_offer": "Oferta más económica",
        "ranking_aria": "Tipo de clasificación",
        "ranking_price": "Sólo precio",
        "ranking_total": "Puntuación total",
        "data_kicker": "Detalle verificable",
        "data_title": "Datos del caso",
        "table_offer": "Oferta",
        "table_amount": "Importe",
        "table_discount_euro": "Baja €",
        "table_discount_percent": "Baja %",
        "table_non_price": "Puntos NO precio",
        "table_status": "Estado",
        "scores_kicker": "Comparación",
        "scores_title": "Puntuación por fórmula",
        "conclusions_kicker": "Lectura del resultado",
        "conclusions_title": "Qué muestra este caso",
        "commercial_kicker": "Análisis profesional",
        "commercial_analysis_cta": "Solicitar un análisis",
        "commercial_case_cta": "Proponer un caso real",
        "footer": "Datos reales anonimizados. La fuente estructurada original no se publica.",
        "profiles": {
            "administracion": {
                "guidance": "Cambia una fórmula, un parámetro o una oferta y observa el efecto sin perder de vista la gráfica.",
                "commercial_title": "¿Quieres analizar tu propia licitación?",
                "commercial_body": "El análisis profesional puede comparar fórmulas, justificar parámetros y documentar su comportamiento sobre ofertas reales.",
            },
            "empresa": {
                "guidance": "Prueba una baja asumible y observa su posición sin convertir el resultado en una recomendación automática.",
                "commercial_title": "¿Necesitas un análisis completo antes de presentar tu oferta?",
                "commercial_body": "El análisis profesional puede incorporar costes, capacidades reales y distintos escenarios de competencia.",
            },
        },
    },
    "lab": {
        "meta_description": "Laboratorio teórico de fórmulas de valoración económica.",
        "page_title": "Laboratorio de fórmulas",
        "product_name": "Laboratorio de fórmulas",
        "product_subtitle": "Comportamiento teórico",
        "intro_kicker": "Teoría antes del caso",
        "intro_title": "Comprender cómo reparte puntos cada fórmula",
        "intro_body": "La curva que se estudia antes de recibir ofertas parte de una hipótesis. Cuando la fórmula depende del conjunto, las referencias observadas pueden producir una curva efectiva diferente.",
        "relative_title": "Relativas",
        "relative_body": "La curva depende de la oferta mínima, la baja máxima u otros datos del conjunto.",
        "absolute_title": "Absolutas",
        "absolute_body": "Una misma baja mantiene su posición con parámetros fijos.",
        "threshold_title": "Umbrales",
        "threshold_body": "La pendiente cambia a partir de una baja definida.",
        "particular_cases_aria": "Casos particulares entre fórmulas",
        "workspace_aria": "Laboratorio interactivo",
        "formula_label": "Fórmula",
        "catalog_aria": "Catálogo de fórmulas",
        "loading_formula": "Cargando fórmula…",
        "real_cases_cta": "Ver en casos reales",
        "family_label": "Familia:",
        "equivalence_group_label": "Grupo de equivalencia:",
        "equivalent_kicker": "Formas equivalentes",
        "equivalent_title": "Misma fórmula, distinta expresión",
        "equivalent_body": "Las variables cambian; la relación matemática no.",
        "offers_expression": "Expresión en ofertas",
        "discounts_expression": "Expresión en bajas",
        "context_label": "Contexto orientativo",
        "contract_works": "Obras",
        "contract_supplies": "Suministros",
        "contract_services": "Servicios",
        "expected_bmax": "Baja máxima esperada",
        "expected_bmax_value_aria": "Baja máxima esperada (valor)",
        "expected_bmax_help": "Hipótesis de trabajo, no dato real.",
        "observed_bmax": "Baja máxima observada",
        "observed_bmax_value_aria": "Baja máxima observada (valor)",
        "observed_bmax_help": "Dato del escenario simulado.",
        "show_resulting_curve": "Mostrar curva resultante",
        "calculating": "Calculando curva teórica…",
        "chart_title": "Curva teórica de la fórmula seleccionada",
        "chart_description": "Comparación de la puntuación teórica para bajas entre cero y treinta por ciento.",
        "dependency_kicker": "Dependencia",
        "zero_discount_kicker": "Baja 0 %",
        "particularities_kicker": "Particularidades",
        "special_cases_kicker": "Casos particulares",
        "equivalences_kicker": "Equivalencias verificadas",
        "catalog_kicker": "Catálogo matemático",
        "catalog_title": "Catálogo canónico revisado",
        "catalog_body": "Nombres públicos, ecuaciones y propiedades contrastados con la implementación actual. Las discrepancias se conservan como asuntos de validación, no se corrigen por intuición.",
        "feedback_kicker": "Participar",
        "feedback_title": "¿Conoces otra fórmula? Proponla",
        "feedback_body": "Seguimos probando nuevas fórmulas y variantes, tanto propias como utilizadas en otras licitaciones.",
        "feedback_discrepancy_cta": "¿Has detectado una discrepancia? Cuéntanoslo",
        "feedback_formula_cta": "Proponer una fórmula",
        "footer": "Las curvas del laboratorio se calculan con el mismo backend validado que los casos reales.",
    },
    "contact": {
        "meta_description": "Contacta con TenderLab para opinar, proponer una fórmula o solicitar un análisis.",
        "page_title": "Contacto · TenderLab",
        "product_name": "TenderLab",
        "product_subtitle": "Fórmulas de Valoración",
        "success_kicker": "Mensaje enviado",
        "success_title": "Gracias. Hemos recibido tu mensaje.",
        "success_body": "Revisaremos la información facilitada y responderemos cuando sea necesario y dispongamos de un email de contacto.",
        "return_analyzer": "Volver al Analizador",
        "return_lab": "Volver al Laboratorio",
        "return_home": "Volver al inicio",
        "intro_kicker": "Contacto",
        "intro_title": "Cuéntanos qué quieres analizar o mejorar",
        "intro_body": "Puedes señalar una discrepancia, proponer una fórmula o un caso real, o solicitar un análisis de tu licitación.",
        "not_configured_notice": "El envío todavía no está configurado en este entorno. Puedes revisar y completar el formulario, pero no se enviará hasta configurar el servicio.",
        "honeypot_label": "No completar este campo",
        "name_label": "Nombre",
        "optional": "Opcional",
        "email_label": "Email",
        "email_help": "Opcional; necesario si deseas respuesta",
        "profile_label": "Perfil",
        "reason_label": "Motivo",
        "message_label": "Mensaje",
        "reference_label": "Enlace al expediente / pliego",
        "reference_placeholder": "https://…",
        "privacy": "Los datos enviados se utilizarán únicamente para responder o valorar la propuesta realizada.",
        "submit": "Enviar mensaje",
        "cancel": "Cancelar",
        "footer": "TenderLab · Herramienta de análisis matemático",
        "profiles": (
            ("administracion", "Administración / técnico redactor"),
            ("control", "Intervención / Jurídico / Control"),
            ("empresa", "Empresa licitadora"),
            ("consultoria", "Consultoría"),
            ("otro", "Otro"),
        ),
        "reasons": (
            ("feedback", "Opinión / corrección"),
            ("formula", "Proponer fórmula"),
            ("caso", "Proponer caso real"),
            ("analisis", "Solicitar análisis"),
            ("otro", "Otro"),
        ),
        "validation": {
            "form_contains_errors": "El formulario contiene errores.",
            "name_too_long": "El nombre no puede superar 100 caracteres.",
            "invalid_email": "El email no tiene un formato válido.",
            "invalid_profile": "Selecciona un perfil válido.",
            "invalid_reason": "Selecciona un motivo válido.",
            "message_too_long": "El mensaje no puede superar 5.000 caracteres.",
            "message_required": "Escribe un mensaje antes de enviarlo.",
            "invalid_reference": "El enlace no tiene un formato válido.",
            "invalid_reference_url": "Introduce una URL http o https válida.",
            "invalid_format": "El formulario no tiene un formato válido.",
            "invalid_size": "El formulario no tiene un tamaño válido.",
            "too_large": "El formulario es demasiado grande.",
            "invalid_fields": "El formulario contiene campos no válidos.",
            "review_fields": "Revisa los campos indicados.",
        },
        "delivery": {
            "rate_limited": "Has enviado varios mensajes en poco tiempo. Espera unos minutos antes de volver a intentarlo.",
            "not_configured": "El envío no está configurado todavía en este entorno. Inténtalo de nuevo más adelante.",
            "failed": "No hemos podido enviar el mensaje. Inténtalo de nuevo dentro de unos minutos.",
        },
        "email": {
            "subject_prefix": "[TenderLab]",
            "name": "Nombre",
            "email": "Email",
            "profile": "Perfil",
            "reason": "Motivo",
            "message": "Mensaje:",
            "reference": "Enlace al expediente / pliego",
            "origin": "Origen",
            "submitted_at": "Fecha/hora servidor",
            "not_provided": "No indicado",
        },
    },
}

